### ISSUE TITLE
OpenAPI format for type IDs

### ISSUE THREAD

**Issue by Le0Developer** [jetify-com/typeid#45]
We currently use an OpenAPI schema like this for TypeID:
```json
"schema": {
    "type": "string",
    "pattern": "^user_[0-7][0-9a-hjkmnq-tv-z]{25}$",
    "example": "user_01jv1sm13xf02v44y3j8b66d7k",
    "format": "typeid"
}
```

As you can see, there's no field for the prefix ("user") that can be programmatically consumed (without parsing the pattern/example).
So I'm wondering, what would the field for that be? `x-typeid-prefix`?

**Comment by klimeryk** [comment]
Thanks for opening this issue - and sharing your regexp for validating TypeID! I just wanted to leave a note that the regexp seems to be missing the `p` character. It is part of the alphabet for the UUID suffix, [as per the specification](https://github.com/jetify-com/typeid/tree/main/spec).

> The encoding uses the following alphabet `0123456789abcdefghjkmnpqrstvwxyz`

So, the regexp should be `^user_[0-7][0-9a-hjkmnpq-tv-z]{25}$`.
Or `^[a-z]([a-z_]{0,61}[a-z])?_[0-7][0-9a-hjkmnpq-tv-z]{25}$` if someone needs a more generic one 🙌

**Comment by Le0Developer** [comment]
🤦
I was close! Thanks, I've edited the comment.

**Comment by mrlubos** [comment]
@Le0Developer how do you end up with `format: typeid` in your OpenAPI spec? Are you doing this manually?

**Comment by loreto** [comment]
I support `format: typeid`. I'm tempted to nest `prefix` inside `x-typeid` to allow for additional fields later.

In OpenAPI YAML, that might look like:
```
    schemas:
      User:
        type: object
        properties:
          id:
            type: string
            format: typeid
            pattern: ...
            x-typeid:
              prefix: user
            example: user_01jv1sm13xf02v44y3j8b66d7k
```

Thoughts?
